### ISSUE TITLE
[Test] AccentUseCase

### ISSUE THREAD

**Issue by YunKi-H** [Team-Hanbae/Hanbae-iOS#109]
## Description

전에 했던 TempoUseCase랑 똑같아보이는 AccentUseCase의 테스트코드를 작성해 봅니다.

## TODO

- [ ] AccentUseCase는 대박, 소박 index를 받아서 MoveNextAccentInterface(templateUseCase)의 해당 위치의 Accent를 강 -> 중 -> 약 -> 없음 으로 rotate 시킵니다.
- [ ] 근데 이 UseCase 내부에는 아무 로직도 없네요?
- [ ] 아무 로직도 없는 UseCase를 굳이 분리해둘 이유가 뭘까요...
- [ ] 이걸 분리해둬서 얻는 장점이 있을까요..?
- [ ] 아니면 분리해두는건 맞긴 한데 얘한테 가야 할 책임을 다른 UseCase가 지고 있는걸까요...?
- [ ] 암튼 배열의 범위 내의 적절한 대박, 소박이 주어질 때
- [ ] 대박이 범위를 벗어날 때 -> 0 미만 || count 이상 둘다
- [ ] 소박이 범위를 벗어날 때 -> 0 미만 || count 이상 둘다
- [ ] 이렇게 5가지 테스트 케이스를 생각해볼 수 있을까요?
- [ ] 테스트를 작성해보다가 의문이 생긴다면 @YunKi-H 를 소환해주세요
